### PR TITLE
Use an embedded dock by default, instead of mod_statusbar

### LINKED ISSUE #115: Make mod_dock the default
Replacing mod_statusbar. Clarify in migration guide (#113)

### PR DESCRIPTION
**Pull request by raboof**
Fixes #115

### CODE REVIEW

**Comment by wilhelmy** [comment]
This means that after installing notion, the dock area will be empty, right?

**Comment by raboof** [comment]
Yes, it will be invisible until you start a dock such as xfce4-panel

**Comment by wilhelmy** [comment]
Right. My dock used to have a minimum size, which was honoured by the previous version of notion I was running and thus presented itself as a 64px high bar on the top of the screen. Ever since I upgraded to master, it is gone, though (I guess because it no longer supports minimum size hints).

**Comment by raboof** [comment]
Sounds like something that would be reasonable to support, filed #149

**Pull request merged**
