### PR TITLE
Use Lua 5.4 if it is found

### LINKED ISSUE #305: Add Lua 5.4 to the build system
It was released a while ago, would be nice to build against it on systems that have it.

### PR DESCRIPTION
**Pull request by wilhelmy**
This closes #305 once merged. Please test, but I don't see anything here https://www.lua.org/manual/5.4/manual.html#8 that we would probably trip over.

### CODE REVIEW

**Comment by raboof** [comment]
nice! if I'm reading https://archlinux.org/packages/extra/x86_64/lua/ right they're already using 5.4

nixos doesn't have 5.4 yet (https://github.com/NixOS/nixpkgs/issues/99261), I'll look into that a bit so I can test ;)

**Review by raboof — APPROVED** [review]
seems to work just fine indeed :+1:

**Comment by raboof** [comment]
@wilhelmy do you want to keep this WIP or is this ready to go?

**Comment by wilhelmy** [comment]
No, I just figured we should test it somewhat extensively, but since master isn't due for release so soon, maybe now would be a good time to merge it.

**Comment by wilhelmy** [comment]
I've been running this for a few days now and it seems stable. Anyone notice any breakage?

**Comment by raboof** [comment]
Seems healthy here!

**Pull request merged**
